<?php

/**
 * Панель управления (административная часть).
 *
 */

Route::get('/',                                 	'SiteController@index')                 ->name('site.index');

Route::resource('actions',                     		'ActionController',                		['names' => resource('action')]);
Route::resource('actiongroups',                     'ActiongroupController',                ['names' => resource('actiongroup')]);
Route::resource('answers',                     		'AnswerController',                		['names' => resource('answer')]);
Route::resource('bannercampaigns',                  'BannercampaignController',             ['names' => resource('bannercampaign')]);
Route::resource('banners',                  		'BannerController',             		['names' => resource('banner')]);
Route::resource('bannerformats',                    'BannerformatController',               ['names' => resource('bannerformat')]);
Route::resource('bannerimpressions',                'BannerimpressionController',           ['names' => resource('bannerimpression')]);
Route::resource('bannerplaces',                	    'BannerplaceController',                ['names' => resource('bannerplace')]);
Route::resource('bannerposts',                	    'BannerpostController',                 ['names' => resource('bannerpost')]);
Route::resource('bannersections',                	'BannersectionController',              ['names' => resource('bannersection')]);
Route::resource('benefits',                    		'BenefitController',               		['names' => resource('benefit')]);
Route::resource('bookmakers',                     	'BookmakerController',                	['names' => resource('bookmaker')]);
Route::resource('bookmakerpictures',                'BookmakerpictureController',           ['names' => resource('bookmakerpicture')]);
Route::resource('bookmakertexts',                   'BookmakertextController',              ['names' => resource('bookmakertext')]);
Route::resource('briefcomments',                    'BriefcommentController',               ['names' => resource('briefcomment')]);
Route::resource('briefs',                     		'BriefController',                		['names' => resource('brief')]);
Route::resource('briefpictures',                    'BriefpictureController',           	['names' => resource('briefpicture')]);
Route::resource('briefstatuses',                    'BriefstatusController',                ['names' => resource('briefstatus')]);
Route::resource('brieftags',                        'BrieftagController',                   ['names' => resource('brieftag')]);
Route::resource('brieftournaments',                 'BrieftournamentController',            ['names' => resource('brieftournament')]);
Route::resource('commentstatuses',                  'CommentstatusController',              ['names' => resource('commentstatus')]);
Route::resource('counters',                     	'CounterController',                	['names' => resource('counter')]);
Route::resource('country',                     		'CountryController',                	['names' => resource('country')]);
Route::resource('customgroups',                     'CustomgroupController',                ['names' => resource('customgroup')]);
Route::resource('customparams',                     'CustomparamController',                ['names' => resource('customparam')]);
Route::resource('customtypes',                      'CustomtypeController',                 ['names' => resource('customtype')]);
Route::resource('deals',                            'DealController',                       ['names' => resource('deal')]);
Route::resource('dealtypes',                        'DealtypeController',                   ['names' => resource('dealtype')]);
Route::resource('events',                           'EventController',                      ['names' => resource('event')]);
Route::resource('forecastcomments',                 'ForecastcommentController',            ['names' => resource('forecastcomment')]);
Route::resource('forecasts',                        'ForecastController',            		['names' => resource('forecast')]);
Route::resource('forecastpictures',                 'ForecastpictureController',            ['names' => resource('forecastpicture')]);
Route::resource('forecaststatuses',                 'ForecaststatusController',             ['names' => resource('forecaststatus')]);
Route::resource('genders',                          'GenderController',                     ['names' => resource('gender')]);
Route::resource('helppictures',                     'HelppictureController',                ['names' => resource('helppicture')]);
Route::resource('helpquestions',                    'HelpquestionController',               ['names' => resource('helpquestion')]);
Route::resource('helpsections',                     'HelpsectionController',                ['names' => resource('helpsection')]);
Route::resource('issues',                           'IssueController',                      ['names' => resource('issue')]);
Route::resource('issuestatuses',                    'IssuestatusController',                ['names' => resource('issuestatus')]);
Route::resource('issuetypes',                       'IssuetypeController',                  ['names' => resource('issuetype')]);
Route::resource('legaldocuments',                	'LegaldocumentController',           	['names' => resource('legaldocument')]);
Route::resource('legaleditions',                	'LegaleditionController',           	['names' => resource('legaledition')]);
Route::resource('matches',                	        'MatchController',           		    ['names' => resource('match')]);
Route::resource('matchstatuses',                	'MatchstatusController',           		['names' => resource('matchstatus')]);
Route::resource('menuitems',                		'MenuitemController',           		['names' => resource('menuitem')]);
Route::resource('menusections',                		'MenusectionController',           		['names' => resource('menusection')]);
Route::resource('noticebans',             		    'NoticebanController',       		    ['names' => resource('noticeban')]);
Route::resource('notices',             		        'NoticeController',       		        ['names' => resource('notice')]);
Route::resource('noticestatuses',             		'NoticestatusController',       		['names' => resource('noticestatus')]);
Route::resource('noticetemplates',             		'NoticetemplateController',       		['names' => resource('noticetemplate')]);
Route::resource('noticetypes',                		'NoticetypeController',           		['names' => resource('noticetype')]);
Route::resource('outcomes',                         'OutcomeController',                    ['names' => resource('outcome')]);
Route::resource('outcometypes',                     'OutcometypeController',                ['names' => resource('outcometype')]);
Route::resource('participants',                     'ParticipantController',                ['names' => resource('participant')]);
Route::resource('postcomments',                     'PostcommentController',                ['names' => resource('postcomment')]);
Route::resource('posts',                     		'PostController',                		['names' => resource('post')]);
Route::resource('postpictures',                     'PostpictureController',           		['names' => resource('postpicture')]);
Route::resource('poststatuses',                     'PoststatusController',                 ['names' => resource('poststatus')]);
Route::resource('posttags',                         'PosttagController',                    ['names' => resource('posttag')]);
Route::resource('posttournaments',                  'PosttournamentController',             ['names' => resource('posttournament')]);
Route::resource('offers',                           'OfferController',                      ['names' => resource('offer')]);
Route::resource('roles',                            'RoleController',                       ['names' => resource('role')]);
Route::resource('seasons',                          'SeasonController',                     ['names' => resource('season')]);
Route::resource('sitepictures',                     'SitepictureController',                ['names' => resource('sitepicture')]);
Route::resource('sitesections',                     'SitesectionController',                ['names' => resource('sitesection')]);
Route::resource('sitetexts',                        'SitetextController',                   ['names' => resource('sitetext')]);
Route::resource('socials',                          'SocialController',                     ['names' => resource('social')]);
Route::resource('sports',                           'SportController',                      ['names' => resource('sport')]);
Route::resource('stages',                           'StageController',                      ['names' => resource('stage')]);
Route::resource('tags',                            	'TagController',                        ['names' => resource('tag')]);
Route::resource('teams',                            'TeamController',                       ['names' => resource('team')]);
Route::resource('tournaments',                      'TournamentController',                 ['names' => resource('tournament')]);
Route::resource('tournamenttypes',                  'TournamenttypeController',             ['names' => resource('tournamenttype')]);
Route::resource('users',							'UserController',                      	['names' => resource('user')]);
Route::resource('usersocials',						'UsersocialController',                 ['names' => resource('usersocial')]);
Route::resource('outcomescopes',					'OutcomescopeController',               ['names' => resource('outcomescope')]);
Route::resource('outcomesubtypes',					'OutcomesubtypeController',             ['names' => resource('outcomesubtype')]);
Route::resource('payments',							'PaymentController',                    ['names' => resource('payment')]);

Route::group(['prefix' => 'ajax'], function () {
	Route::post('actions',                     		'ActionController@search')        	    ->name('action.search');
	Route::post('actiongroups',                     'ActiongroupController@search')        	->name('actiongroup.search');
	Route::post('banners',                          'BannerController@search')              ->name('banner.search');
	Route::post('bannercampaigns',                  'BannercampaignController@search')      ->name('bannercampaign.search');
	Route::post('bannerformats',                    'BannerformatController@search')        ->name('bannerformat.search');
	Route::post('bannerplaces',                     'BannerplaceController@search')         ->name('bannerplace.search');
	Route::post('bannerposts',                      'BannerpostController@search')          ->name('bannerpost.search');
	Route::post('bannersections',                   'BannersectionController@search')       ->name('bannersection.search');
	Route::post('bookmakers',                       'BookmakerController@search')        	->name('bookmaker.search');
	Route::post('bookmakertexts',                   'BookmakertextController@search')     	->name('bookmakertext.search');
	Route::post('briefs',                   		'BriefController@search')       		->name('brief.search');
	Route::post('briefstatuses',                   	'BriefstatusController@search')       	->name('briefstatus.search');
	Route::post('commentstatuses',                  'CommentstatusController@search')     	->name('commentstatus.search');
	Route::post('countries',                   		'CountryController@search')     		->name('country.search');
	Route::post('customgroups',                   	'CustomgroupController@search')     	->name('customgroup.search');
	Route::post('customtypes',                   	'CustomtypeController@search')     		->name('customtype.search');
	Route::post('dealtypes',                        'DealtypeController@search')        	->name('dealtype.search');
	Route::post('events',                        	'EventController@search')        		->name('event.search');
	Route::post('issues',                    		'IssueController@search')        		->name('issue.search');
	Route::post('issuestatuses',                    'IssuestatusController@search')        	->name('issuestatus.search');
	Route::post('issuetypes',                       'IssuetypeController@search')        	->name('issuetype.search');
	Route::post('matchstatuses',                    'MatchstatusController@search')        	->name('matchstatus.search');
	Route::post('forecasts',                        'ForecastController@search')        	->name('forecast.search');
	Route::post('forecaststatuses',                 'ForecaststatusController@search')      ->name('forecaststatus.search');
	Route::post('genders',                 			'GenderController@search')      		->name('gender.search');
	Route::post('helpquestions',                    'HelpquestionController@search')        ->name('helpquestion.search');
	Route::post('helpsections',                     'HelpsectionController@search')        	->name('helpsection.search');
	Route::post('legaldocuments',                   'LegaldocumentController@search')       ->name('legaldocument.search');
	Route::post('matches',                   		'MatchController@search')       		->name('match.search');
	Route::post('menusections',                   	'MenusectionController@search')       	->name('menusection.search');
	Route::post('noticestatuses',                   'NoticestatusController@search')        ->name('noticestatus.search');
	Route::post('noticetypes',                      'NoticetypeController@search')          ->name('noticetype.search');
	Route::post('outcomes',                   		'OutcomeController@search')       		->name('outcome.search');
	Route::post('outcometypes',                   	'OutcometypeController@search')       	->name('outcometype.search');
	Route::post('posts',                   			'PostController@search')       			->name('post.search');
	Route::post('poststatuses',                   	'PoststatusController@search')       	->name('poststatus.search');
	Route::post('roles',                   			'RoleController@search')       			->name('role.search');
	Route::post('seasons',                     		'SeasonController@search')        		->name('season.search');
	Route::post('sitesections',                     'SitesectionController@search')     	->name('sitesection.search');
	Route::post('sitetexts',                        'SitetextController@search')     	    ->name('sitetext.search');
	Route::post('socials',                     		'SocialController@search')        		->name('social.search');
	Route::post('sports',                     		'SportController@search')        		->name('sport.search');
	Route::post('stages',                     		'StageController@search')        		->name('stage.search');
	Route::post('tags',                     		'TagController@search')        			->name('tag.search');
	Route::post('teams',                     		'TeamController@search')        		->name('team.search');
	Route::post('tournaments',                     	'TournamentController@search')        	->name('tournament.search');
	Route::post('tournamenttypes',                  'TournamenttypeController@search')      ->name('tournamenttype.search');
	Route::post('users',                   			'UserController@search')       			->name('user.search');
	Route::post('offers',                 			'OfferController@search')       		->name('offer.search');
	Route::post('outcomescopes',           			'OutcomescopeController@search')   		->name('outcomescope.search');
	Route::post('outcomesubtypes',         			'OutcomesubtypeController@search')   	->name('outcomesubtype.search');
	Route::post('payments',         				'PaymentController@search')   			->name('payment.search');
});

